# Generated by Django 4.2.2 on 2023-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_options_alter_user_managers_user_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.CharField(default="2020-12-12", max_length=255),
            preserve_default=False,
        ),
    ]
