# Generated by Django 4.2.2 on 2023-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_bio_user_other_details_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="other_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
