# Generated by Django 4.2.2 on 2023-06-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_bio_alter_user_other_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="other_details",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
