# Generated by Django 4.2.2 on 2023-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_like_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtag",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
