# Generated by Django 4.2.2 on 2023-06-29 12:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_bio_alter_user_other_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True, upload_to=user.models.user_image_file_path
            ),
        ),
    ]
