# Generated by Django 4.2.2 on 2023-06-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_post_delete_userfollowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="username", max_length=60),
        ),
    ]
